#include "driver.h"
#include "Interrupt.tmh"

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, PcieInterruptCreate)
#endif

NTSTATUS
PcieInterruptCreate(
_In_ PDEVICE_CONTEXT DevExt
)
/*++
Routine Description:

Configure and create the WDFINTERRUPT object.
This routine is called by EvtDeviceAdd callback.

Arguments:

DevExt      Pointer to our DEVICE_EXTENSION

Return Value:

NTSTATUS code

--*/
{
	NTSTATUS  status = STATUS_SUCCESS;
	WDF_INTERRUPT_CONFIG        InterruptConfig;

	PAGED_CODE();
	DbgPrint("zhu:-->PcieInterruptCreate<--");
//#ifdef DEBUG_ZHU
//	TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "--> %!FUNC!");
//#endif

	WDF_INTERRUPT_CONFIG_INIT(&InterruptConfig,
		PcieEvtInterruptIsr,
		PcieEvtInterruptDpc);

	InterruptConfig.EvtInterruptEnable = PcieEvtInterruptEnable;
	InterruptConfig.EvtInterruptDisable = PcieEvtInterruptDisable;

	// JOHNR: Enable testing of the DpcForIsr Synchronization
	InterruptConfig.AutomaticSerialization = TRUE;

	//
	// Unlike WDM, framework driver should create interrupt object in EvtDeviceAdd and
	// let the framework do the resource parsing and registration of ISR with the kernel.
	// Framework connects the interrupt after invoking the EvtDeviceD0Entry callback
	// and disconnect before invoking EvtDeviceD0Exit. EvtInterruptEnable is called after
	// the interrupt interrupt is connected and EvtInterruptDisable before the interrupt is
	// disconnected.
	//
	status = WdfInterruptCreate(DevExt->Device,
		&InterruptConfig,
		WDF_NO_OBJECT_ATTRIBUTES,
		&DevExt->Interrupt);

	if (!NT_SUCCESS(status)) {
#ifdef DEBUG_ZHU
		TraceEvents(TRACE_LEVEL_ERROR, TRACE_DRIVER,
			"WdfInterruptCreate failed: %!STATUS!", status);
#endif
		return status;
	}

#ifdef DEBUG_ZHU
	TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "<-- %!FUNC!");
#endif
	DbgPrint("zhu:-->PcieInterruptCreate  successful!<--");
	return status;
}

BOOLEAN
PcieEvtInterruptIsr(
_In_ WDFINTERRUPT Interrupt,
_In_ ULONG        MessageID
)
/*++
Routine Description:

Interrupt handler for this driver. Called at DIRQL level when the
device or another device sharing the same interrupt line asserts
the interrupt. The driver first checks the device to make sure whether
this interrupt is generated by its device and if so clear the interrupt
register to disable further generation of interrupts and queue a
DPC to do other I/O work related to interrupt - such as reading
the device memory, starting a DMA transaction, coping it to
the request buffer and completing the request, etc.

Arguments:

Interupt   - Handle to WDFINTERRUPT Object for this device.
MessageID  - MSI message ID (always 0 in this configuration)

Return Value:

TRUE   --  This device generated the interrupt.
FALSE  --  This device did not generated this interrupt.

--*/
{
	BOOLEAN             isRecognized = FALSE;
	PDEVICE_CONTEXT     devExt;
	ULONG               intStatus;

	UNREFERENCED_PARAMETER(MessageID);
	DbgPrint("zhu:-->PcieEvtInterruptIsr<--");


#ifdef DEBUG_ZHU
	TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "--> %!FUNC!");
#endif

	devExt = DeviceGetContext(WdfInterruptGetDevice(Interrupt));
	if (devExt->MemBar0Base){
		intStatus = PcieDeviceGetInterrupt(devExt->MemBar0Base);

		//if (intStatus){
			PcieDeviceDisableInterrupt(devExt->MemBar0Base);
			PcieDeviceClearInterrupt(devExt->MemBar0Base);
			devExt->IntStatus = intStatus;
			WdfInterruptQueueDpcForIsr(devExt->Interrupt);
			isRecognized = TRUE;
		//}
	}

	return isRecognized;
}

VOID
PcieEvtInterruptDpc(
_In_ WDFINTERRUPT Interrupt,
_In_ WDFDEVICE    Device
)
/*++

Routine Description:

DPC callback for ISR. Please note that on a multiprocessor system,
you could have more than one DPCs running simulataneously on
multiple processors. So if you are accesing any global resources
make sure to synchrnonize the accesses with a spinlock.

Arguments:

Interupt  - Handle to WDFINTERRUPT Object for this device.
Device    - WDFDEVICE object passed to InterruptCreate

Return Value:

--*/
{
	PDEVICE_CONTEXT     devExt;
	NTSTATUS             status = STATUS_SUCCESS;

	UNREFERENCED_PARAMETER(Device);
	DbgPrint("zhu:-->PcieEvtInterruptDpc<--");
#ifdef DEBUG_ZHU
	TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "--> %!FUNC!");
#endif

	devExt = DeviceGetContext(WdfInterruptGetDevice(Interrupt));
	

	//if (devExt->IntStatus)
	//{
		if (devExt->CurrentRequestMode == 0xf)
		{
			// Acquire lock						
			WdfInterruptAcquireLock(Interrupt);

			status = PcieTimerStop(devExt->ReadTimer);

			PVOID out_buffer;
			size_t out_bufsize;
			status = WdfRequestRetrieveOutputBuffer(devExt->ReadRequest, 1, &out_buffer, &out_bufsize);
			if (!NT_SUCCESS(status)){
				WdfRequestCompleteWithInformation(devExt->ReadRequest, status, 0);
				return;
			}
			if (devExt->ReadTimeout == FALSE)
			{
				ULONG data = PcieDeviceReadReg(devExt->MemBar2Base, 0x10);
				((PULONG)out_buffer)[0] = data;
				if (devExt->ReadRequest){
					WdfRequestCompleteWithInformation(devExt->ReadRequest, status, sizeof(ULONG));
					DbgPrint("zhu: ReadRequestComplete!");
				}
				else{
					DbgPrint("zhu:ReadRequest is null!");
				}
				

			}
			else{
				DbgPrint("zhu:TimerOut!");
			}

			// Release lock
			WdfInterruptReleaseLock(Interrupt);
			
		} 
		else if (devExt->CurrentRequestMode == 0xff)
		{
			// Acquire lock						
			WdfInterruptAcquireLock(Interrupt);

			status = PcieTimerStop(devExt->IoWriteTimer);

			if (devExt->IoWriteTimeout == FALSE)
			{
				if (devExt->IoWriteRequest){
					WdfRequestCompleteWithInformation(devExt->IoWriteRequest, status, 0);
					DbgPrint("zhu: IoWriteRequestComplete!");
				}
				else{
					DbgPrint("zhu:IoWriteRequest is null!");
				}
			}
			else{
				DbgPrint("zhu:TimerOut!");
			}
			

			// Release lock
			WdfInterruptReleaseLock(Interrupt);
		}
		else
		{
			

			// Acquire lock						
			WdfInterruptAcquireLock(Interrupt);

			status = PcieTimerStop(devExt->WriteTimer);

			if (devExt->WriteTimeout == FALSE)
			{
				if (devExt->WriteRequest)
				{
					WdfRequestCompleteWithInformation(devExt->WriteRequest, status, devExt->WriteDmaLength);
					DbgPrint("zhu:writeRequestComplete!");
				}
				else{
					DbgPrint("zhu:writeRequest is null!");
				}
				
			}
			else{
				DbgPrint("zhu:TimerOut!");
			}

			// Release lock
			WdfInterruptReleaseLock(Interrupt);
		}

}

NTSTATUS
PcieEvtInterruptEnable(
_In_ WDFINTERRUPT Interrupt,
_In_ WDFDEVICE    Device
)
/*++

Routine Description:

Called by the framework at DIRQL immediately after registering the ISR with the kernel
by calling IoConnectInterrupt.

Return Value:

NTSTATUS
--*/
{
	NTSTATUS  status = STATUS_SUCCESS;
	PDEVICE_CONTEXT  	devExt;

	UNREFERENCED_PARAMETER(Device);

	DbgPrint("zhu:->PcieEvtInterruptEnable<--");

	devExt = DeviceGetContext(WdfInterruptGetDevice(Interrupt));

	/*PcieDeviceWriteReg(devExt->MemBar0Base, 0x188, 0x1);*/
//	if (devExt->MemBar0Base){
//		PcieDeviceEnableInterrupt(devExt->MemBar0Base);
//	}
//
//#ifdef DEBUG_ZHU
//	TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "<-- %!FUNC!");
//#endif
	return status;
}

NTSTATUS
PcieEvtInterruptDisable(
_In_ WDFINTERRUPT Interrupt,
_In_ WDFDEVICE    Device
)
/*++

Routine Description:

Called by the framework at DIRQL before Deregistering the ISR with the kernel
by calling IoDisconnectInterrupt.

Return Value:

NTSTATUS
--*/
{
	NTSTATUS  status = STATUS_SUCCESS;
	PDEVICE_CONTEXT  	devExt;

	UNREFERENCED_PARAMETER(Device);

//#ifdef DEBUG_ZHU
//	TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "--> %!FUNC!");
//#endif
	DbgPrint("zhu:-->PcieEvtInterruptDisable<--");
	devExt = DeviceGetContext(WdfInterruptGetDevice(Interrupt));
	if (devExt->MemBar0Base){
		PcieDeviceDisableInterrupt(devExt->MemBar0Base);
	}

	
//
//#ifdef DEBUG_ZHU
//	TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "<-- %!FUNC!");
//#endif
	return status;
}